### ISSUE TITLE
Valeurs anormales

### ISSUE THREAD

**Issue by pascal-shom** [lblanc/grafana-integration#3]
Bonjour
Lors de l'utilisation du script **datacore_get_perf.py** , j'ai régulièrement des valeurs anormales sur la datation des enregistrements dans influxdb

Un enregistrement correct:
DataCore_Physical_disk,instance=SSY1-NVMe1\ on\ orsw-2018-0001,objectname=DataCore\ Physical\ disk,host=orsw-2018-0001,id={8a8ea79e-2e9d-471b80c4-9c1a23af9c49},Serial=FE49_0104_80CF_0400.,Type=4,Caption=SSY1-NVMe1 DiskStatus=1 **1593703097084000000**

Un enregistrement incorrect:
DataCore_Physical_disk,instance=MSA2-V4-SSY2\ on\ orsw-2018-0002,objectname=DataCore\ Physical\ disk,host=orsw-2018-0002,id={07fdf856-2260-4eba-9ffc-3574f040c281},Serial=00c0ff268f150000dfbdad5d01000000,Type=4,Caption=MSA2-V4-SSY2 MaxReadWriteTime=0 **253402300799999000**

J'ai patché le script pour recaler la datation à la date courante  (+ 1" pour ne pas ecarter les valeurs correctes), mais ce n'est surement pas une bonne solution car cela apporte un biais dans les mesures.
_...
import time
recaltime=1
....
min(int((time.time()+recaltime)*1000000000),int(data["Performances"]["CollectionTime"][6:-2])*1000000))_

Est-ce une anomalie de l'API ? ou autre....
Votre aide serait bienvenue

En vous remerciant par avance de l'aide que vous pourriez m'apporter
Pascal

**Comment by lblanc** [comment]
Bonjour,

Le collectiontime dépend de l’heure du serveur DataCore, il y a peu être un problème de ce côté là.

**Comment by pascal-shom** [comment]
Bonjour, 

Probablement, mais ce n'est pas systématique. Les DataCores sont synchro via NTP. 
Il me faudrait une requête simple via curl pour comprendre, mais je n'ai pas trouvé. 

Merci pour votre travail

**Comment by lblanc** [comment]
Bonjour,

Voici un exemple:
curl --location --request GET 'http://X.X.X.X/RestService/rest.svc/1.0/servers' \
--header 'ServerHost: X.X.X.X' \
--header 'Authorization: Basic Administrator Password'
